export const queryKeys = {
  me: ['me'] as const,
  customers: ['customers'] as const,
  customer: (id: number) => ['customers', id] as const,
  sites: ['sites'] as const,
  site: (id: number) => ['sites', id] as const,
  assets: ['assets'] as const,
  asset: (id: number) => ['assets', id] as const,
  technicians: ['technicians'] as const,
  technician: (id: number) => ['technicians', id] as const,
  parts: ['parts'] as const,
  part: (id: number) => ['parts', id] as const,
  workOrders: ['work-orders'] as const,
  workOrder: (id: number) => ['work-orders', id] as const,
  serviceReports: ['service-reports'] as const,
  serviceReport: (id: number) => ['service-reports', id] as const,
  users: ['users'] as const,
  user: (id: number) => ['users', id] as const,
  dashboard: {
    stats: ['dashboard', 'stats'] as const,
    workload: ['dashboard', 'workload'] as const,
    sla: ['dashboard', 'sla'] as const,
    avgResolution: ['dashboard', 'avg-resolution'] as const,
    partsConsumption: ['dashboard', 'parts-consumption'] as const,
    overTime: ['dashboard', 'over-time'] as const,
  },
}
