import {
  lucideArrowRight,
  lucideBarChart3,
  lucideBell,
  lucideBellRing,
  lucideBoxes,
  lucideBuilding2,
  lucideCheck,
  lucideCheckCheck,
  lucideCheckCircle2,
  lucideChevronDown,
  lucideChevronRight,
  lucideClipboardCheck,
  lucideClipboardList,
  lucideCopy,
  lucideEye,
  lucideEyeOff,
  lucideFileText,
  lucideGlobe,
  lucideKeyRound,
  lucideLayoutDashboard,
  lucideLogOut,
  lucideMapPin,
  lucidePackage,
  lucidePencil,
  lucidePlay,
  lucidePlus,
  lucideQuote,
  lucideRefreshCw,
  lucideSearch,
  lucideSettings,
  lucideShield,
  lucideShieldCheck,
  lucideStar,
  lucideTrash2,
  lucideUpload,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideWrench,
  lucideX,
} from '@ng-icons/lucide';

export const appIcons = {
  arrowRight: lucideArrowRight,
  barChart3: lucideBarChart3,
  bell: lucideBell,
  bellRing: lucideBellRing,
  boxes: lucideBoxes,
  building2: lucideBuilding2,
  check: lucideCheck,
  checkCheck: lucideCheckCheck,
  checkCircle2: lucideCheckCircle2,
  chevronDown: lucideChevronDown,
  chevronRight: lucideChevronRight,
  clipboardCheck: lucideClipboardCheck,
  clipboardList: lucideClipboardList,
  copy: lucideCopy,
  eye: lucideEye,
  eyeOff: lucideEyeOff,
  fileText: lucideFileText,
  globe: lucideGlobe,
  keyRound: lucideKeyRound,
  layoutDashboard: lucideLayoutDashboard,
  logOut: lucideLogOut,
  mapPin: lucideMapPin,
  package: lucidePackage,
  pencil: lucidePencil,
  play: lucidePlay,
  plus: lucidePlus,
  quote: lucideQuote,
  refreshCw: lucideRefreshCw,
  search: lucideSearch,
  settings: lucideSettings,
  shield: lucideShield,
  shieldCheck: lucideShieldCheck,
  star: lucideStar,
  trash2: lucideTrash2,
  user: lucideUser,
  userPlus: lucideUserPlus,
  upload: lucideUpload,
  users: lucideUsers,
  wrench: lucideWrench,
  x: lucideX,
};
